// Mocks generated by Mockito 5.4.6 from annotations
// in waterboard/test/test_helpers/test_util.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/cupertino.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:waterboard/services/ros_comms/ros.dart' as _i4;
import 'package:waterboard/services/ros_comms/ros_subscription.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeROSSubscription_1 extends _i1.SmartFake
    implements _i3.ROSSubscription {
  _FakeROSSubscription_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ROSImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockROSImpl extends _i1.Mock implements _i4.ROSImpl {
  @override
  _i2.ValueNotifier<_i4.ROSConnectionState> get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _FakeValueNotifier_0<_i4.ROSConnectionState>(
              this,
              Invocation.getter(#connectionState),
            ),
            returnValueForMissingStub:
                _FakeValueNotifier_0<_i4.ROSConnectionState>(
                  this,
                  Invocation.getter(#connectionState),
                ),
          )
          as _i2.ValueNotifier<_i4.ROSConnectionState>);

  @override
  Map<String, _i3.ROSSubscription> get subs =>
      (super.noSuchMethod(
            Invocation.getter(#subs),
            returnValue: <String, _i3.ROSSubscription>{},
            returnValueForMissingStub: <String, _i3.ROSSubscription>{},
          )
          as Map<String, _i3.ROSSubscription>);

  @override
  void startConnectionLoop() => super.noSuchMethod(
    Invocation.method(#startConnectionLoop, []),
    returnValueForMissingStub: null,
  );

  @override
  void reconnect() => super.noSuchMethod(
    Invocation.method(#reconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.ROSSubscription subscribe(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [topic]),
            returnValue: _FakeROSSubscription_1(
              this,
              Invocation.method(#subscribe, [topic]),
            ),
            returnValueForMissingStub: _FakeROSSubscription_1(
              this,
              Invocation.method(#subscribe, [topic]),
            ),
          )
          as _i3.ROSSubscription);

  @override
  void propagateData(String? topic, Map<String, dynamic>? data) =>
      super.noSuchMethod(
        Invocation.method(#propagateData, [topic, data]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ROSSubscriptionImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockROSSubscriptionImpl extends _i1.Mock
    implements _i3.ROSSubscriptionImpl {
  @override
  _i2.ValueNotifier<Map<String, dynamic>> get notifier =>
      (super.noSuchMethod(
            Invocation.getter(#notifier),
            returnValue: _FakeValueNotifier_0<Map<String, dynamic>>(
              this,
              Invocation.getter(#notifier),
            ),
            returnValueForMissingStub:
                _FakeValueNotifier_0<Map<String, dynamic>>(
                  this,
                  Invocation.getter(#notifier),
                ),
          )
          as _i2.ValueNotifier<Map<String, dynamic>>);

  @override
  String get topic =>
      (super.noSuchMethod(
            Invocation.getter(#topic),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#topic),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#topic),
            ),
          )
          as String);

  @override
  bool get isStale =>
      (super.noSuchMethod(
            Invocation.getter(#isStale),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void onData(Map<String, dynamic>? data) => super.noSuchMethod(
    Invocation.method(#onData, [data]),
    returnValueForMissingStub: null,
  );
}
